export const FORM_XML_ROOT = "form";

export const FORM_XML_TOP_LEVEL_ORDER = [
    "ancestor",
    "hiddencontrols",
    "controlDescriptions",
    "tabs",
    "header",
    "footer",
    "events",
    "formLibraries",
    "externaldependencies",
    "formparameters",
    "clientresources",
    "Navigation",
    "DisplayConditions",
    "RibbonDiffXml"
] as const;

export type FormXmlTopLevelElementName = typeof FORM_XML_TOP_LEVEL_ORDER[number];

export const FORM_XML_OPAQUE_ELEMENTS = new Set([
    "RibbonDiffXml"
]);

export const FORM_XML_ENUMS: Record<string, readonly string[]> = {
    BehaviorInBulkEditForm: ["Disabled", "EnabledButNoRender", "Enabled"],
    CrmEventType: ["DataEvent", "ControlEvent"],
    FormatType: [
        "SingleLineOfText",
        "WholeNumber",
        "DecimalNumber",
        "Currency",
        "Date",
        "DateTime",
        "DateAndTime",
        "Url",
        "Ticker",
        "Email",
        "TextArea"
    ],
    FormParameterAttributeType: [
        "Boolean",
        "DateTime",
        "Double",
        "EntityType",
        "Integer",
        "Long",
        "Object",
        "PositiveInteger",
        "SafeString",
        "UniqueId",
        "UnsignedInt"
    ],
    FormParameterPassAsAttributeType: ["QueryString"],
    GridResizeType: ["Auto", "Fixed", "AutoWithFixedMax"],
    ImageHorizontalAlignmentType: ["Left", "Right", "Center", "NotSet"],
    ImageVerticalAlignmentType: ["Top", "Middle", "Bottom", "NotSet"],
    RelationshipRoleOrdinalType: ["1", "2"],
    WebResourceSizeType: ["StretchToFit", "StretchMaintainAspectRatio", "Original", "Specific"],
    solutionactionType: ["Added", "Removed", "Modified"]
};

export const FORM_XML_BOOLEAN_ATTRIBUTES = new Set([
    "active",
    "application",
    "auto",
    "autoexpand",
    "availableforphone",
    "AvailableOffline",
    "collapsible",
    "disabled",
    "enablerelatedinformation",
    "expanded",
    "FallbackForm",
    "hasmargin",
    "indicationOfSubgrid",
    "ischartcell",
    "ispreviewcell",
    "isrequired",
    "isstreamcell",
    "istilecell",
    "isunbound",
    "tilespresent",
    "relatedInformationCollapsed",
    "showbar",
    "showImage",
    "showlabel",
    "showlabels",
    "shownavigationbar",
    "userspacer",
    "ValidForCreate",
    "ValidForUpdate",
    "visible",
    "verticallayout"
]);

export const FORM_XML_NUMBER_ATTRIBUTES = new Set([
    "columns",
    "colspan",
    "formFactor",
    "labelwidth",
    "locklevel",
    "maxWidth",
    "Order",
    "rowheight",
    "rowspan",
    "Sequence"
]);

export const FORM_XML_ARRAY_CHILDREN = new Set([
    "data",
    "controlDescription",
    "customControl",
    "tab",
    "column",
    "section",
    "row",
    "cell",
    "Library",
    "event",
    "Handler",
    "dependency",
    "label",
    "Title",
    "NavBarArea",
    "NavBarItem",
    "NavBarByRelationshipItem",
    "Privilege",
    "querystringparameter",
    "Role",
    "internaljscriptfile",
    "internalcssfile",
    "internaljscriptvariable",
    "webresource",
    "TargetEntity",
    "StreamObject"
]);

export const FORM_XML_TEXT_ELEMENTS = new Set([
    "Url",
    "PassParameters",
    "Security",
    "Scrolling",
    "Border",
    "Preload",
    "IsPassword",
    "IsColorValue",
    "Height",
    "Width",
    "AltText",
    "SizeType",
    "ShowInROF",
    "ShowOnMobileClient",
    "HorizontalAlignment",
    "VerticalAlignment",
    "Data",
    "WebResourceId",
    "ReadOnly",
    "ShowDialogs",
    "IsViewExpandable",
    "HideToolbar",
    "ToolbarJSON",
    "ExpandedToolbarJSON",
    "HiddenToolbarJSON",
    "ClassName",
    "ViewName",
    "EntityLogicalName",
    "DefaultViewId",
    "IsDeDupLookup",
    "UnboundLookupStyle",
    "ViewId",
    "IsUserView",
    "IsUserChart",
    "RelationshipName",
    "RelationshipRoleOrdinal",
    "TargetEntityType",
    "AutoExpand",
    "RecordsPerPage",
    "MaxRowsBeforeScroll",
    "EnableQuickFind",
    "EnableJumpBar",
    "EnableViewPicker",
    "ViewIds",
    "ChartGridMode",
    "VisualizationId",
    "EnableChartPicker",
    "EnableContextualActions",
    "TeamTemplateId",
    "GridUIMode",
    "ReferencePanelSubgridIconUrl",
    "HeaderColorCode",
    "PowerBIGroupId",
    "PowerBIDashboardId",
    "TileId",
    "TileUrl",
    "Type",
    "EnableInMobile",
    "FilterRelationshipName",
    "DependentAttributeName",
    "DependentAttributeType",
    "AutoResolve",
    "ResolveEmailAddress",
    "DefaultViewReadOnly",
    "ViewPickerReadOnly",
    "AllowFilterOff",
    "DisableMru",
    "DisableQuickFind",
    "DisableViewPicker",
    "AvailableViewIds",
    "IsInlineNewEnabled",
    "InlineViewIds",
    "UnboundLookupTypes",
    "UnboundLookupBrowse",
    "UnboundLookupControlType",
    "ShowAsBreadcrumbControl",
    "MaxLength",
    "Format",
    "IsTitle",
    "MinValue",
    "MaxValue",
    "Precision",
    "DefaultValue",
    "OptionSetName",
    "OptionSetId",
    "QuickForms",
    "ControlMode",
    "ReferencePanelQuickFormCollectionIconUrl",
    "DisplayAsCustomer360Tile",
    "DefaultTabId",
    "ShowArticleTab",
    "FilterResults",
    "AllowChangingFiltersOnUI",
    "ShowLanguageFilter",
    "ShowDepartmentFilter",
    "EnableAutoSuggestions",
    "SearchForAutoSuggestionsUsing",
    "EnableRating",
    "ShowRatingUsing",
    "AutoSuggestionSource",
    "SelectPrimaryCustomer",
    "NumberOfResults",
    "ShowContextualActions",
    "ActionList",
    "ReferencePanelSearchWidgetIconUrl",
    "SelectDefaultLanguage",
    "OrderByActivityWall",
    "SortActivityWall",
    "EmailConversationView",
    "UClientUniqueName",
    "UClientModules",
    "UClientDefaultModuleForCreateExperience",
    "UClientShowFilterPane",
    "UClientExpandFilterPane",
    "UClientCreateActivityUsing",
    "UClientDisplayActivityUsing",
    "UClientRecordPerPage",
    "UClientActivities",
    "UClientOrderBy",
    "UClientActivityCardMap",
    "UClientDisplayActivityHeaderUsing",
    "UClientSortActivitiesByValue",
    "LinkControlDefinitionId",
    "ShowLinkControlLabel",
    "AddressField",
    "FailureTimeField",
    "SuccessConditionName",
    "SuccessConditionValue",
    "FailureConditionName",
    "FailureConditionValue",
    "WarningConditionName",
    "WarningConditionValue",
    "CancelConditionName",
    "CancelConditionValue",
    "PauseConditionName",
    "PauseConditionValue",
    "ShowAsTiles",
    "LogicalEntityName",
    "QueueId",
    "QueueViewId",
    "EntityViewId",
    "SavedQueryID",
    "QueueViewIdForSavedQuery",
    "AttributeLogicalName",
    "TimeFrame"
]);

export const FORM_XML_ELEMENT_ORDER: Record<string, readonly string[]> = {
    form: FORM_XML_TOP_LEVEL_ORDER,
    tabs: ["tab"],
    tab: ["labels", "tabheader", "tabfooter", "columns", "events"],
    columns: ["column"],
    column: ["sections"],
    sections: ["section"],
    section: ["labels", "rows"],
    rows: ["row"],
    row: ["cell"],
    cell: ["labels", "control", "events"],
    control: ["labels", "parameters"],
    parameters: [
        "Url", "PassParameters", "Security", "Scrolling", "Border", "Preload", "IsPassword", "IsColorValue",
        "Height", "Width", "AltText", "SizeType", "ShowInROF", "ShowOnMobileClient", "HorizontalAlignment", "VerticalAlignment", "Data", "WebResourceId",
        "ReadOnly", "ShowDialogs", "IsViewExpandable", "HideToolbar", "ToolbarJSON", "ExpandedToolbarJSON", "HiddenToolbarJSON", "ClassName", "ViewName",
        "TargetEntities", "ViewId", "IsUserView", "IsUserChart", "RelationshipName", "RelationshipRoleOrdinal", "TargetEntityType", "AutoExpand", "RecordsPerPage",
        "MaxRowsBeforeScroll", "EnableQuickFind", "EnableJumpBar", "EnableViewPicker", "ViewIds", "ChartGridMode", "VisualizationId", "EnableChartPicker",
        "EnableContextualActions", "TeamTemplateId", "GridUIMode", "ReferencePanelSubgridIconUrl", "HeaderColorCode", "PowerBIGroupId", "PowerBIDashboardId",
        "TileId", "TileUrl", "Type", "EnableInMobile", "DefaultViewId", "FilterRelationshipName", "DependentAttributeName", "DependentAttributeType",
        "AutoResolve", "ResolveEmailAddress", "DefaultViewReadOnly", "ViewPickerReadOnly", "AllowFilterOff", "DisableMru", "DisableQuickFind",
        "DisableViewPicker", "AvailableViewIds", "EntityLogicalName", "IsInlineNewEnabled", "InlineViewIds", "UnboundLookupTypes", "UnboundLookupBrowse",
        "UnboundLookupControlType", "ShowAsBreadcrumbControl", "MaxLength", "Format", "IsTitle", "MinValue", "MaxValue", "Precision", "DefaultValue",
        "OptionSetName", "OptionSetId", "QuickForms", "ControlMode", "ReferencePanelQuickFormCollectionIconUrl", "DisplayAsCustomer360Tile",
        "DefaultTabId", "ShowArticleTab", "FilterResults", "AllowChangingFiltersOnUI", "ShowLanguageFilter", "ShowDepartmentFilter", "EnableAutoSuggestions",
        "SearchForAutoSuggestionsUsing", "EnableRating", "ShowRatingUsing", "AutoSuggestionSource", "SelectPrimaryCustomer", "NumberOfResults",
        "ShowContextualActions", "ActionList", "ReferencePanelSearchWidgetIconUrl", "SelectDefaultLanguage", "OrderByActivityWall", "SortActivityWall",
        "EmailConversationView", "UClientUniqueName", "UClientModules", "UClientDefaultModuleForCreateExperience", "UClientShowFilterPane",
        "UClientExpandFilterPane", "UClientCreateActivityUsing", "UClientDisplayActivityUsing", "UClientRecordPerPage", "UClientActivities",
        "UClientOrderBy", "UClientActivityCardMap", "UClientDisplayActivityHeaderUsing", "UClientSortActivitiesByValue", "LinkControlDefinitionId",
        "ShowLinkControlLabel", "AddressField", "FailureTimeField", "SuccessConditionName", "SuccessConditionValue", "FailureConditionName",
        "FailureConditionValue", "WarningConditionName", "WarningConditionValue", "CancelConditionName", "CancelConditionValue", "PauseConditionName",
        "PauseConditionValue", "StreamObjects", "AttributeLogicalName", "TimeFrame"
    ],
    TargetEntities: ["TargetEntity"],
    TargetEntity: ["EntityLogicalName", "DefaultViewId", "IsDeDupLookup", "UnboundLookupStyle"],
    StreamObjects: ["ShowAsTiles", "StreamObject"],
    StreamObject: ["LogicalEntityName", "QueueId", "QueueViewId", "EntityViewId", "SavedQueryID", "QueueViewIdForSavedQuery"],
    events: ["event"],
    event: ["Handlers", "InternalHandlers", "dependencies"],
    Handlers: ["Handler"],
    InternalHandlers: ["Handler"],
    dependencies: ["dependency"],
    formLibraries: ["Library"],
    externaldependencies: ["dependency"],
    formparameters: ["querystringparameter"],
    Navigation: ["NavBarAreas", "NavBar"],
    NavBarAreas: ["NavBarArea"],
    NavBarArea: ["Titles"],
    NavBar: ["NavBarItem", "NavBarByRelationshipItem"],
    NavBarItem: ["Titles"],
    NavBarByRelationshipItem: ["Titles", "ToolTip", "Privileges"],
    ToolTip: ["Titles"],
    Privileges: ["Privilege"],
    Titles: ["Title"],
    DisplayConditions: ["Everyone", "Role"],
    clientresources: ["internalresources", "isvresources"],
    internalresources: ["clientincludes", "clientvariables"],
    isvresources: ["clientincludes"],
    clientincludes: ["internaljscriptfile", "internalcssfile", "webresource"],
    clientvariables: ["internaljscriptvariable"],
    hiddencontrols: ["data"],
    controlDescriptions: ["controlDescription"],
    controlDescription: ["customControl"],
    customControl: ["parameters"]
};
